### ISSUE TITLE
이 부분이 잘 이해가 안가서 질문드립니다!!

### ISSUE THREAD

**Issue by imdudu1** [kkamagui/mint64os-examples#1]
> 어떤 값으로 세그먼트 레지스터를 초기화해야 할까요? MINT64 OS에서는 0x07C0으 로 초기화 했습니다. 그 이유는 BIOS가 부트 로더를 디스크에서 읽어 메모리에 복사하는 위치가 0x7C00이기 때문입니다. 또한 부트 로더의 코드(Code Segment)와 데이터(Data Segment)는 0x7C00부터 512바이트 범위에 존재하므로 CS와 DS 세그먼트 레지스터를 모두 0x07C0으로 설정했 습니다.

이 부분에서 0x7c00과 0x07c0의 관계를 잘 모르겠습니다...ㅠ

**Comment by imdudu1** [comment]
Aㅏ... 세그먼테이션은 16을 곱하는걸 까먹고 이런 질문을 올렸네요 ...

**Comment by kkamagui** [comment]
@aid95 님 안녕하세요, 벌써 스스로 답을 찾으셨군요. ^^
말씀하신 내용이 맞습니다.
