### ISSUE TITLE
_

### ISSUE THREAD

**Issue by lastime1650** [kkamagui/mint64os-examples#3]

**Comment by kkamagui** [comment]
안녕하세요, @lastime1650님.
보내주신 화면을 보니까 -Werror 컴파일 옵션이 들어가서 Warning이 Error로 처리된 것 같습니다.

현재 설치하신 binutils-2.34+1git.de9c1b7cfe-1버전은 정식 버전이 아니라 Git에서 당겨온 임시 버전이니,
바로 이전의 정식 버전인 binutils-2.34-1을 설치 후에 빌드하시면 될 것 같습니다.

책을 구매해주셔서 감사드리구요, 
8시간 동안이나 포기하지 않으시고 시도해주셔서 감사합니다.

책이 좀 두껍지만 완독하시길 빕니다. ^^

한승훈 드림.

**Comment by lastime1650** [comment]
제가 그때 진짜 너무 화가나서 감정이 들어가 쓴것 같습니다 죄송합니다....
 끝까지 완독하며 포기하지않고 도전하겠습니다 ..
